// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Contact struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt time.Time
}
